M48
; DRILL file {KiCad 9.0.3} date 2026-05-18T21:28:48-0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-18T21:28:48-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.500
%
G90
G05
T1
X104.0Y-77.5
X104.0Y-113.5
X207.0Y-77.5
X207.0Y-113.5
M30
